import type { SeoLandingPageProps } from "@/components/SeoLandingPage";

export const seoPages: Record<string, SeoLandingPageProps> = {
  "agence-marketing-renovation": {
    pageTitle: "Agence marketing rénovation",
    metaDescription: "Agendac, agence marketing spécialisée pour les sociétés de rénovation de l'habitat. Génération de leads, publicité, SEO, sites web et tournages.",
    canonical: "/agence-marketing-renovation",
    h1: "Agence marketing spécialisée rénovation de l'habitat",
    intro: "Agendac est l'agence marketing dédiée aux sociétés de rénovation de l'habitat de plus de 1M€ de CA en France, Suisse romande et Belgique. Nous aidons les dirigeants à structurer leur acquisition client et générer plus de demandes qualifiées.",
    problem: {
      title: "Le problème que rencontrent les entreprises de rénovation",
      body: "La plupart des sociétés de rénovation dépendent du bouche-à-oreille, de leads achetés non qualifiés ou de campagnes publicitaires mal pilotées. Résultat : une visibilité instable, des cycles de vente longs et une rentabilité publicitaire imprévisible."
    },
    solution: {
      title: "La solution Agendac",
      body: "Nous concevons un système d'acquisition complet : publicité Meta Ads et Google Ads, SEO local, site internet conçu pour convertir, prise de rendez-vous qualifiés et tournages professionnels qui renforcent la confiance. Tout est piloté par la donnée et adapté aux réalités du marché de la rénovation."
    },
    services: {
      title: "Nos services pour les sociétés de rénovation",
      items: [
        "Publicité Meta Ads, Facebook Ads et Instagram Ads",
        "Campagnes Google Ads ciblées rénovation",
        "Génération de leads et prospects qualifiés",
        "Prise de rendez-vous commerciaux qualifiés",
        "SEO local et référencement Google",
        "Création et refonte de site internet",
        "Tournages vidéo professionnels",
        "Tunnels de vente et landing pages",
      ]
    },
    why: {
      title: "Pourquoi choisir Agendac",
      items: [
        "Spécialiste exclusif du marché de la rénovation de l'habitat et du BTP",
        "Plus de 1M€ de CA accompagnés : interlocuteurs au bon niveau",
        "Méthodes éprouvées sur la France, la Suisse romande et la Belgique",
        "Pilotage transparent du coût par lead et du retour publicitaire",
        "Une équipe complète : ads, SEO, web, vidéo et conversion",
      ]
    },
    faq: [
      { question: "À qui s'adresse Agendac ?", answer: "Agendac accompagne les CEO, directeurs commerciaux, marketing et communication de sociétés de rénovation de l'habitat réalisant plus de 1M€ de chiffre d'affaires annuel." },
      { question: "Sur quels secteurs Agendac travaille-t-elle ?", answer: "Isolation, menuiseries, fenêtres, panneaux solaires, pompes à chaleur, piscines, énergies renouvelables, extension de maison, rénovation énergétique, bâtiment et BTP." },
      { question: "Sur quels marchés géographiques Agendac intervient-elle ?", answer: "France, Suisse romande et Belgique francophone." },
      { question: "Quelle différence avec une agence marketing généraliste ?", answer: "Agendac connaît les cycles de vente, les saisonnalités, les coûts d'acquisition et les attentes commerciales propres à la rénovation de l'habitat." },
    ],
  },
  "agence-marketing-renovation-energetique": {
    pageTitle: "Agence marketing rénovation énergétique",
    metaDescription: "Agence marketing spécialisée rénovation énergétique : isolation, panneaux solaires, pompes à chaleur. Génération de leads qualifiés et publicité performante.",
    canonical: "/agence-marketing-renovation-energetique",
    h1: "Agence marketing rénovation énergétique",
    intro: "Agendac aide les entreprises de rénovation énergétique — isolation, panneaux solaires, pompes à chaleur, énergies renouvelables — à générer des demandes qualifiées et structurer leur acquisition client.",
    problem: { title: "Un marché concurrentiel et complexe", body: "Le marché de la rénovation énergétique est saturé de leads achetés de mauvaise qualité, de réglementations changeantes et d'une concurrence agressive sur les CPL publicitaires. Beaucoup d'entreprises n'arrivent plus à rentabiliser leurs campagnes." },
    solution: { title: "Un système d'acquisition adapté à la rénovation énergétique", body: "Agendac construit des campagnes ciblées, une qualification rigoureuse, un site internet conçu pour convertir et un suivi du coût par rendez-vous qualifié. Vous savez exactement combien vous coûte chaque opportunité commerciale." },
    services: { title: "Nos services rénovation énergétique", items: ["Génération de leads isolation, PAC, panneaux solaires", "Publicité Meta Ads et Google Ads ciblées", "SEO et référencement local", "Sites internet à forte conversion", "Prise de rendez-vous qualifiés", "Tournages chantiers et témoignages clients"] },
    why: { title: "Pourquoi Agendac pour la rénovation énergétique", items: ["Connaissance fine des aides et mécanismes (MaPrimeRénov', CEE...)", "Maîtrise des audiences chaudes et froides en rénovation énergétique", "Approche orientée rendez-vous qualifiés, pas volume de leads", "Reporting transparent et pilotage par la donnée"] },
    faq: [
      { question: "Agendac travaille-t-elle avec les installateurs PAC et panneaux solaires ?", answer: "Oui. C'est l'un de nos secteurs de prédilection avec l'isolation et les énergies renouvelables." },
      { question: "Faites-vous de l'achat de leads ?", answer: "Non. Nous construisons votre propre canal d'acquisition, plus durable et plus rentable que l'achat de leads génériques." },
    ],
  },
  "agence-marketing-btp": {
    pageTitle: "Agence marketing BTP",
    metaDescription: "Agence marketing spécialisée BTP, bâtiment et travaux. Acquisition client, génération de leads B2B et B2C, publicité, SEO et sites internet.",
    canonical: "/agence-marketing-btp",
    h1: "Agence marketing BTP, bâtiment et travaux",
    intro: "Agendac est l'agence marketing dédiée aux entreprises du BTP, du bâtiment et des travaux. Nous accompagnons les dirigeants pour développer leur acquisition client et structurer un marketing rentable.",
    problem: { title: "Le BTP a longtemps négligé son marketing", body: "Beaucoup d'entreprises du BTP s'appuient encore sur la recommandation et n'ont pas de système marketing structuré. Quand les chantiers se raréfient, elles n'ont aucun levier rapide pour relancer la demande." },
    solution: { title: "Un marketing pensé pour le BTP", body: "Agendac met en place un système d'acquisition complet adapté aux cycles de vente du bâtiment : publicité, SEO, site internet, prise de rendez-vous, contenu vidéo et suivi des opportunités commerciales." },
    services: { title: "Nos services pour le BTP", items: ["Génération de leads B2B et B2C", "Campagnes Google Ads et Meta Ads", "SEO local et national", "Sites internet et landing pages", "Vidéos chantiers et corporate", "Prise de rendez-vous qualifiés"] },
    why: { title: "Pourquoi Agendac pour le BTP", items: ["Spécialiste du BTP, du bâtiment, des travaux et de la rénovation", "Compréhension des appels d'offres et des cycles longs", "Approche pilotée par le ROI", "Équipe complète marketing, web et vidéo"] },
    faq: [
      { question: "Travaillez-vous avec les entreprises générales du bâtiment ?", answer: "Oui, ainsi qu'avec les sociétés spécialisées : couverture, plomberie, électricité, maçonnerie, menuiserie." },
      { question: "Faites-vous du B2B ?", answer: "Oui. Nous accompagnons aussi les entreprises BTP qui ciblent des prescripteurs ou grands comptes." },
    ],
  },
  "agence-communication-renovation": {
    pageTitle: "Agence communication rénovation",
    metaDescription: "Agence communication spécialisée rénovation et BTP. Image de marque, contenu, vidéo, réseaux sociaux et site internet pour entreprises de rénovation.",
    canonical: "/agence-communication-renovation",
    h1: "Agence communication rénovation",
    intro: "Agendac aide les sociétés de rénovation à construire une marque forte, crédible et reconnaissable. Communication, image, contenu, vidéo et présence digitale.",
    problem: { title: "Une communication faible nuit à la conversion", body: "Sans marque claire, sans preuves visibles et sans contenu différenciant, même les meilleurs artisans peinent à se démarquer et à convaincre les prospects." },
    solution: { title: "Une communication structurée et professionnelle", body: "Agendac aligne votre identité, votre contenu, vos vidéos et vos canaux digitaux pour renforcer votre crédibilité et améliorer votre taux de conversion commercial." },
    services: { title: "Nos services communication", items: ["Identité de marque et positionnement", "Tournages corporate et chantiers", "Gestion des réseaux sociaux", "Création de contenu", "Site internet et refonte", "Relations presse et notoriété locale"] },
    why: { title: "Pourquoi Agendac", items: ["Connaissance fine du secteur rénovation et BTP", "Approche centrée sur la conversion, pas seulement l'image", "Production vidéo internalisée", "Méthodologie éprouvée auprès de dirigeants"] },
    faq: [
      { question: "Faites-vous de la création de logo ?", answer: "Oui, dans le cadre d'un travail global d'identité de marque." },
      { question: "Gérez-vous les réseaux sociaux au quotidien ?", answer: "Oui, nous proposons un accompagnement complet sur LinkedIn, Instagram, Facebook, YouTube et TikTok selon votre cible." },
    ],
  },
  "agence-generation-leads-renovation": {
    pageTitle: "Agence génération de leads rénovation",
    metaDescription: "Génération de leads qualifiés pour sociétés de rénovation de l'habitat : isolation, menuiseries, panneaux solaires, pompes à chaleur, piscines.",
    canonical: "/agence-generation-leads-renovation",
    h1: "Agence génération de leads rénovation",
    intro: "Agendac met en place des systèmes de génération de leads qualifiés pour les sociétés de rénovation de l'habitat. Pas de leads achetés à bas prix : votre propre canal, vos propres prospects.",
    problem: { title: "Les leads achetés ne convertissent plus", body: "Les leads vendus à plusieurs entreprises en parallèle sont saturés, peu motivés et coûteux à transformer. Beaucoup de dirigeants en rénovation cherchent une alternative durable." },
    solution: { title: "Votre propre machine à leads", body: "Agendac construit un système qui génère des leads exclusifs, alignés avec votre offre et votre zone géographique, et les fait avancer jusqu'au rendez-vous commercial qualifié." },
    services: { title: "Notre système de génération de leads", items: ["Stratégie d'acquisition multi-canal", "Publicité Meta Ads et Google Ads", "Landing pages à forte conversion", "Qualification et prise de rendez-vous", "CRM et suivi commercial", "Optimisation du coût par rendez-vous"] },
    why: { title: "Pourquoi Agendac", items: ["Leads exclusifs, pas mutualisés", "Pilotage transparent du CPL et du coût par RDV", "Spécialisation rénovation et BTP", "Méthodologie éprouvée"] },
    faq: [
      { question: "Combien coûte un lead rénovation avec Agendac ?", answer: "Le coût dépend du secteur, de la zone et de la maturité du marché. Nous établissons une estimation après audit de votre situation." },
      { question: "Garantissez-vous un volume de leads ?", answer: "Nous nous engageons sur une méthode et un pilotage rigoureux. Le volume final dépend de votre budget publicitaire et de votre offre." },
    ],
  },
  "agence-generation-leads-btp": {
    pageTitle: "Agence génération de leads BTP",
    metaDescription: "Génération de leads qualifiés pour entreprises du BTP, du bâtiment et des travaux. Système d'acquisition complet pour dirigeants exigeants.",
    canonical: "/agence-generation-leads-btp",
    h1: "Agence génération de leads BTP",
    intro: "Agendac construit des systèmes de génération de leads pour les entreprises du BTP, du bâtiment et des travaux. Une approche structurée pour développer votre acquisition client.",
    problem: { title: "Les entreprises BTP manquent de canaux structurés", body: "Sans système marketing, le flux d'opportunités est imprévisible et dépend trop de la conjoncture ou du bouche-à-oreille." },
    solution: { title: "Un système d'acquisition stable", body: "Agendac met en place un canal d'acquisition fiable, mesurable et pilotable pour vos équipes commerciales." },
    services: { title: "Notre offre BTP", items: ["Stratégie d'acquisition", "Publicité ciblée Google et Meta", "Sites et landing pages dédiés", "Prise de rendez-vous qualifiés", "Reporting et CRM"] },
    why: { title: "Pourquoi Agendac", items: ["Spécialisation BTP et rénovation", "Pilotage par la donnée", "Équipe complète marketing et vidéo"] },
    faq: [
      { question: "Travaillez-vous avec les TPE ?", answer: "Nous accompagnons principalement les entreprises de plus de 1M€ de CA, capables d'absorber un flux régulier de demandes." },
    ],
  },
  "generation-leads-renovation": {
    pageTitle: "Génération de leads rénovation",
    metaDescription: "Système d'acquisition de prospects qualifiés pour entreprises de rénovation de l'habitat. Leads exclusifs, pas mutualisés.",
    canonical: "/generation-leads-renovation",
    h1: "Génération de leads pour entreprises de rénovation",
    intro: "Agendac vous aide à générer vos propres leads qualifiés en rénovation de l'habitat — isolation, menuiseries, panneaux solaires, pompes à chaleur, piscines, extension de maison.",
    problem: { title: "Les leads génériques ne suffisent plus", body: "Achetés en masse, partagés entre concurrents, peu engagés : les leads génériques saturent et coûtent de plus en plus cher à convertir." },
    solution: { title: "Vos leads, vos prospects, votre marque", body: "Nous bâtissons votre propre canal d'acquisition pour des prospects exclusifs, mieux qualifiés et plus rentables." },
    services: { title: "Ce que nous mettons en place", items: ["Audit de votre situation actuelle", "Stratégie publicitaire Meta et Google", "Landing pages qui convertissent", "Qualification téléphonique", "Prise de rendez-vous", "Pilotage CPL et coût par RDV"] },
    why: { title: "Pourquoi Agendac", items: ["Leads exclusifs", "Spécialisation rénovation", "Pilotage transparent", "Approche commerciale, pas uniquement marketing"] },
    faq: [
      { question: "En combien de temps voit-on les premiers leads ?", answer: "Les premières demandes arrivent généralement sous 2 à 4 semaines après le lancement, selon le secteur et la zone." },
    ],
  },
  "publicite-renovation": {
    pageTitle: "Publicité rénovation Meta & Google Ads",
    metaDescription: "Campagnes Meta Ads, Facebook Ads et Google Ads pour entreprises de rénovation. Pilotage du ROAS et du coût par lead.",
    canonical: "/publicite-renovation",
    h1: "Publicité en ligne pour entreprises de rénovation",
    intro: "Agendac conçoit, lance et optimise les campagnes publicitaires des sociétés de rénovation : Meta Ads, Facebook Ads, Instagram Ads et Google Ads.",
    problem: { title: "La publicité mal pilotée brûle votre budget", body: "Sans tracking, sans audiences fines, sans landing pages adaptées et sans qualification, les campagnes coûtent cher et ne convertissent pas." },
    solution: { title: "Un pilotage publicitaire rigoureux", body: "Nous structurons les comptes, le tracking, les créas, les audiences et les pages d'atterrissage pour maximiser le ROAS et minimiser le coût par lead qualifié." },
    services: { title: "Nos campagnes", items: ["Meta Ads (Facebook + Instagram)", "Google Ads (Search, Performance Max, YouTube)", "Création des visuels et vidéos publicitaires", "Tracking et conversions", "A/B test landing pages", "Reporting hebdomadaire"] },
    why: { title: "Pourquoi Agendac", items: ["Spécialiste publicité rénovation", "Maîtrise des audiences froides et chaudes", "Pilotage du coût par RDV, pas uniquement par lead"] },
    faq: [
      { question: "Quel budget publicitaire mensuel faut-il prévoir ?", answer: "Cela dépend de votre marché. Nous définissons un budget cohérent avec vos objectifs de chiffre d'affaires." },
    ],
  },
  "seo-renovation": {
    pageTitle: "SEO rénovation et référencement",
    metaDescription: "Référencement naturel pour entreprises de rénovation, rénovation énergétique, menuiserie, isolation, piscine et BTP. SEO local et national.",
    canonical: "/seo-renovation",
    h1: "SEO rénovation : visibilité durable sur Google",
    intro: "Agendac vous aide à dominer Google sur les requêtes stratégiques de votre secteur de rénovation et à transformer cette visibilité en demandes qualifiées.",
    problem: { title: "Sans SEO, vous êtes dépendant des annonces", body: "Sans présence organique, chaque visiteur coûte de l'argent en publicité. Le SEO offre un actif durable et rentable sur le long terme." },
    solution: { title: "Une stratégie SEO orientée business", body: "Audit, mots-clés, contenu, optimisation technique, netlinking, fiche Google Business : nous construisons votre autorité sur les sujets qui génèrent du chiffre d'affaires." },
    services: { title: "Nos services SEO", items: ["Audit SEO complet", "Stratégie de mots-clés", "Création de contenu", "SEO technique", "SEO local et Google Maps", "Optimisation IA / GEO", "Netlinking ciblé"] },
    why: { title: "Pourquoi Agendac", items: ["Spécialisation rénovation et BTP", "Approche orientée conversion", "Maîtrise du SEO local", "Veille permanente sur Google et l'IA"] },
    faq: [
      { question: "En combien de temps voit-on les résultats SEO ?", answer: "Les premiers signaux apparaissent en 3 à 6 mois selon la concurrence et l'état initial du site." },
    ],
  },
  "site-internet-renovation": {
    pageTitle: "Création de site internet rénovation",
    metaDescription: "Création et refonte de sites internet pour sociétés de rénovation. Sites, landing pages et tunnels de conversion qui transforment les visiteurs.",
    canonical: "/site-internet-renovation",
    h1: "Création de site internet pour sociétés de rénovation",
    intro: "Agendac crée et refait les sites internet des sociétés de rénovation pour renforcer leur crédibilité et convertir plus de visiteurs en demandes qualifiées.",
    problem: { title: "Un site qui ne convertit pas est un site qui coûte", body: "Beaucoup de sites de rénovation sont jolis mais ne génèrent aucune demande. Pas de structure commerciale, pas de preuves, pas de tunnel clair." },
    solution: { title: "Des sites pensés pour la conversion", body: "Nous concevons des sites rapides, mobiles, optimisés SEO et pensés comme un véritable outil commercial avec landing pages dédiées et tunnels de prise de rendez-vous." },
    services: { title: "Nos prestations web", items: ["Création de site vitrine", "Refonte complète", "Landing pages campagnes", "Tunnel de prise de rendez-vous", "SEO on-page", "Performance et Core Web Vitals"] },
    why: { title: "Pourquoi Agendac", items: ["Approche commerciale et pas uniquement esthétique", "SEO intégré dès la conception", "Spécialiste rénovation et BTP", "Maintenance et évolution continue"] },
    faq: [
      { question: "Combien de temps prend la création d'un site ?", answer: "Entre 4 et 8 semaines selon la complexité et la disponibilité du contenu." },
    ],
  },
  "tournage-video-renovation": {
    pageTitle: "Tournage vidéo professionnel rénovation",
    metaDescription: "Production vidéo professionnelle pour entreprises de rénovation : corporate, chantiers, témoignages clients, drone et publicités.",
    canonical: "/tournage-video-renovation",
    h1: "Tournage vidéo professionnel pour entreprises de rénovation",
    intro: "Agendac réalise des tournages professionnels pour mettre en avant les sociétés de rénovation de l'habitat : équipes, chantiers, savoir-faire et témoignages clients.",
    problem: { title: "Sans vidéo, vous perdez en confiance", body: "Les prospects veulent voir vos chantiers, vos équipes et vos clients satisfaits avant de signer. Sans contenu vidéo crédible, vous laissez la place à vos concurrents." },
    solution: { title: "Des vidéos qui vendent", body: "Nous produisons des vidéos corporate, des vidéos de chantiers, des témoignages clients et des publicités vidéo prêtes à diffuser sur Meta, Google, YouTube et votre site internet." },
    services: { title: "Nos formats vidéo", items: ["Vidéos corporate", "Reportages chantiers", "Témoignages clients", "Vidéos publicitaires Meta et YouTube", "Prises de vue par drone", "Capsules réseaux sociaux"] },
    why: { title: "Pourquoi Agendac", items: ["Équipe vidéo internalisée", "Connaissance fine du secteur rénovation", "Vidéos pensées pour la conversion", "Cohérence avec votre stratégie marketing globale"] },
    faq: [
      { question: "Vous déplacez-vous sur tout le territoire ?", answer: "Oui, en France, en Suisse romande et en Belgique francophone." },
    ],
  },
};
